config/routes.rb
Rails.application.routes.draw do

  resources :want_to_sees, except: [:show, :new, :create, :edit, :update]
  resources :actors, except: [:index]
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :directors, except: [:index]
  get "search" => "search#search", :as => :search

  resources :movies do
    resources :reviews, except: [:show, :index]
    resources :want_to_sees, only: [:new, :create, :edit, :update]
  end

  root 'movies#index'
end

app/models/actor.rb
class Actor < ApplicationRecord
  validate :date_validation
  has_and_belongs_to_many :movies

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates_presence_of :name, :surname, :biography

  def date_validation
    if birth.nil?
      errors.add(:birth, 'Birth must be set')
    elsif birth >= Date.today
      errors.add(:birth, 'Birth can not be in future or today')
    end
  end

  def age
    today = Date.today
    age = today.year - birth.year
    age -= 1 if Date.today < (birth + age.years)
    age
  end

  def select_label
    "#{name} #{surname} " + birth.strftime("%d.%m.%Y")
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /actors/1
  # GET /actors/1.json
  def show
    @movies = {}
    @actor.movies.each do |m|
      if @movies.key?(m.year)
        @movies[m.year].add(m)
      else
        @movies[m.year] = Set.new
        @movies[m.year].add(m)
      end
    end
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor / Astress was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to movies_path, notice: 'Actor / Actress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :surname, :birth, :biography, :image)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<head>
</head>

<%= simple_form_for @actor, html: { multipart: true } do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor / actress from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Name', error: 'Name of actor / actress must be set.' %>
    <%= f.input :surname, label: 'Surname', error: 'Surname of actor / actress must be set.' %>
    <%= f.input :birth, as: :date, html5: true, label: 'Birth', error: 'Birth of actor / actress must be set.'  %>
    <%= f.input :biography, label: 'Biography', error: 'Biography of actor / actress must be set.' %>
    <%= f.input :image, label: 'Image', error: 'Image must be set' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-danger" %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<html>
  <div class="jumbotron">
    <h1>Edit Actor / Actress</h1>

    <%= render 'form', actor: @actor %>

    <%= link_to 'Back', @actor  %>
  </div>
</html>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors / Actresses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Birth</th>
      <th>Biography</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.surname %></td>
        <td><%= actor.birth %></td>
        <td><%= actor.biography %></td>
        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Update', edit_actor_path(actor) %></td>
        <td><%= link_to 'Delete', actor, method: :delete, data: { confirm: 'Are you sure to delete this actor / actress?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new', new_actor_path %>

app/views/actors/new.html.erb
<html>
  <div class="jumbotron">
    <h1>New Actor / Actress</h1>

    <%= render 'form', actor: @actor %>

    <%= link_to 'Back', movies_path %>
  </div>
</html>

app/views/actors/show.html.erb
<head>
</head>

  <div class="actor-info">
    <div class="row">
      <div class="col-md-2">
        <% if @actor.image_file_name%>
          <%= image_tag @actor.image.url(:medium), :size => "225x300" %>
        <% else %>
          <%= image_tag url_to_asset("no-person"), :size => "225x300" %>
        <% end %>
      </div>
      <div class="col-md-8 col-md-offset-1">
        <h1 class: "btn btn-danger"><%= @actor.name + " " + @actor.surname %></h1>

        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>actor / actress</strong></td>
                <td></td>
              </tr>
              <tr>
                <td><strong>Name:</strong></td>
                <td><%= @actor.name %></td>
              </tr>
              <tr>
                <td><strong>Surname:</strong></td>
                <td><%= @actor.surname %></td>
              </tr>
              <tr>
                <td><strong>Birth:</strong></td>
                <td><%= @actor.birth.strftime("%d.%m.%Y") + " ( age: " + @actor.age.to_s + " )" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_actor_path(@actor) %> |
      <%= link_to 'Delete', @actor, method: :delete, data: { confirm: 'Are you sure to delete this actor / actress?' } %> |
    <% end %>
    <%= link_to 'Back', movies_path %>

  </div>

<div class="col-md-8">
  <div class="actor-biography">
    <tr>
      <p></p>
      <h5><strong>Biography:</strong></h5>
      <p></p>
      <td><%= @actor.biography%></td>
    </tr>
  </div>
</div>

<div class="col-md-4">
  <div class="actor-list-movies">
    <h5><strong>List of movies</strong></h5>
    <div class="table-responsive">
      <table class="table">
        <tbody>
          <% if @actor.movies.empty? %>
            <h3>No movie</h3>
          <% else %>

            <% @movies.each do |k, set| %>
                <tr>
                  <td><strong><%= k %></strong></td>
                  <td>
                    <% set.each do |movie| %>
                      <p>
                        <div class="star-rating" data-score= <%= movie.avg_ratting %> > 
                          <strong><%= link_to (movie.title), movie, :style=> 'color:#0000ff' %> </strong>
                        </div>
                      </p>
                    <% end %>
                  </td>
               </tr>    
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>


<script>
  $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score')
      }
  });
</script>