config/routes.rb
Rails.application.routes.draw do

  resources :want_to_sees, except: [:show, :new, :create, :edit, :update]
  resources :actors, except: [:index]
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :directors, except: [:index]
  get "search" => "search#search", :as => :search

  resources :movies do
    resources :reviews, except: [:show, :index]
    resources :want_to_sees, only: [:new, :create, :edit, :update]
  end

  root 'movies#index'
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :want_to_sees, dependent: :destroy
  belongs_to :category
  belongs_to :director
  has_and_belongs_to_many :actors

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :title, :year, :lengthMinutes, :director, :description, :actors
  validate :length_validation
  validate :year_validation

  self.per_page = 1

  def avg_ratting
    @reviews = Review.where(movie_id: id)
    return 0 if @reviews.blank?
    @reviews.average(:rating).round(2)
  end

  def length_validation
    errors.add(:lengthMinutes, 'must be more then 0') if lengthMinutes && (lengthMinutes <= 0)
  end

  def year_validation
    errors.add(:year, 'must be more then 0') if year && (year <= 0)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    if user_signed_in?
      @wantSee = want_this_week
      @wantSee = @wantSee.paginate(page: params[:want_this_week], per_page: 4)
    end
    @movies = Movie.all.order("created_at DESC")
    @movies = @movies[0..4] if @movies.length > 5
  end

  def show
    @write = false
    @want = false
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    @reviews = @reviews.paginate(page: params[:reviews], per_page: 5)
    if user_signed_in?
      @write = true if Review.where(
        movie_id: @movie.id, user_id: current_user.id).blank?
      @want = true if WantToSee.where(
        movie_id: @movie.id, user_id: current_user.id).blank?
    end
  end

  def new
    @movie = current_user.movies.build
  end

  def edit
  end

  def create
    @movie = current_user.movies.build(movie_params)
    @actors = Actor.where(:id => params[:movie][:actors])
    @movie.actors << @actors

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @movie.user_id = current_user.id
      @actors = Actor.where(:id => params[:movie][:actors])
      @movie.actors.destroy_all
      @movie.actors << @actors

      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_path, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :director, :year,
        :lengthMinutes, :image, :category_id, :director_id)
    end

    def want_this_week
      endWeek = Date.today + (7 - Date.today.wday).modulo(7)
      startWeek = endWeek - 6
      WantToSee.where(date: startWeek..endWeek, user_id: current_user.id).order("date ASC")
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<script>
  $(function($){
    $("#selectCategory").select2({
      theme: "bootstrap",
      placeholder: "Select category"
    });
  });

  $(function($){
    $("#selectDirector").select2({
      theme: "bootstrap",
      placeholder: "Select director"
    });
  });

$(function($) { 
  $("#selectActors").select2({
    theme: "bootstrap",
    placeholder: "Select actors and actresses",
    tags: true
  });
});

</script>

<%= simple_form_for @movie, html: { multipart: true } do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">

    <div class="field">
      <%= f.label :category_id, label: 'Category', required: true %>
        <%= f.select(:category_id, Category.all.collect{|c| [c.name, c.id]},{}, {:required => true, :multiple => false, :id =>"selectCategory", :style => "width: 100%", data: "live-search"} ) %>
    </div>
    <p></p>
    <%= f.input :title, required: true, label: 'Title', error: 'Title of movie must be set.' %>
    <%= f.input :year, label: 'Year', error: 'Year of movie must be set.' %>
    <%= f.input :lengthMinutes, label: 'Length (min)', error: 'Length of movie must be set.' %>
    
    <div class="field">
    <%= f.label :director_id, label: 'Director', required: true %>
    <%= f.select(:director_id, Director.all.collect{|d| [d.name + " " + d.surname + " " + d.birth.strftime("%d.%m.%Y"), d.id]},{}, {:required => true, :multiple => false, :id =>"selectDirector", :style => "width: 100%", :data => {:placeholder => 'Choose director'}, data: "live-search"} ) %>
    </div>
    <p></p>

    <div class="field">
      <%= f.label :actors, label: 'Actors / Actresses', required: true %>
      <%= f.select(:actors, options_for_select(Actor.all.collect{|a| [a.name + " " + a.surname + " " + a.birth.strftime("%d.%m.%Y"), a.id]}, :selected => @movie.actor_ids), {}, {:required => true, :multiple => true, :id =>"selectActors", :style => "width: 100%", data: "live-search"} ) %>
    </div>

    <%= f.input :description, label: 'Description', error: 'Description must be set', message: 'Description must be set' %>
    <%= f.input :image, label: 'Image', error: 'Image must be set' %>
    <p></p>


  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-danger" %>
  </div>

<% end %>

app/views/movies/edit.html.erb
<html>
  <div class="jumbotron">
    <h1>Edit Movie</h1>

    <%= render 'form', movie: @movie %>

    <%= link_to 'Back', @movie %>
  </div>
</html>

app/views/movies/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

app/views/movies/index.html.erb
<head>
</head>

<div class="container">
  <% if !user_signed_in? %>
    <div class="jumbotron">
      <h1>Welcome on pages about movies</h1>
      <p>If you want to edit movies or write review you have to sing up.</p>
      <%= link_to "Sing up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  <% else %>
    <div class="jumbotron">
      <h1>Welcome <%= User.where(id: current_user.id).first.nickname %></h1>
      <p>This week you want to see those movies:</p>
    </div>
  
    <div class="main-list">
      <table style="width:100%">
        <thead>
          <tr>
            <th>Movie</th>
            <th>Date</th>
            <th>Ratting</th>
          </tr>
        </thead>

        <tbody>
          <% if @wantSee.empty? %>
            <tr>
              <td>No movie</td>
            </tr>
          <% end %>
          <% @wantSee.each do |want_to_see| %>
            <tr>
              <td><%= link_to (Movie.where(id:want_to_see.movie_id).first.title), Movie.where(id:want_to_see.movie_id).first, :style=> 'color:#0000ff' %></td>
              <td><%= want_to_see.date.strftime("%d.%m.%Y") %></td>
              <td>
                <div class="star-rating" data-score=<%= Movie.where(id:want_to_see.movie_id).first.avg_ratting %> ></div>
              </td>
              <td><%= link_to 'Edit', edit_movie_want_to_see_path(id:want_to_see.id, movie_id:want_to_see.movie_id) %></td>
              <td><%= link_to 'Delete', want_to_see, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @wantSee, renderer: BootstrapPagination::Rails,
        :param_name => 'want_this_week', previous_label: "Prev", next_label: "Next",
        inner_window: 1, outer_window: 0 %>
    </div>
  <% end %>
</div>

<div class="container">
  <br>
  <div id="mySlider" class="carousel slide" style="margin: auto" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#mySlider" data-slide-to="0" class="active"></li>
      <li data-target="#mySlider" data-slide-to="1"></li>
      <li data-target="#mySlider" data-slide-to="2"></li>
      <li data-target="#mySlider" data-slide-to="3"></li>
      <li data-target="#mySlider" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <% @movies.each do |movie| %>
        <% if movie == @movies.first%>
          <div class="item active">
            <% if movie.image_file_name%>
              <a href= <%=movie_path(movie) %>>
                <img class="img-responsive center-block" src= <%="#{movie.image.url(:medium)}"%> alt=<%="#{movie.title}"%> width="400" height="600">
              </a>
            <% else %>
              <a href=<%=movie_path(movie) %>>
                <img class="img-responsive center-block" src= <%="#{url_to_asset("no-movie")}"%> alt=<%="#{movie.title}"%> width="400" height="600">
              </a>
            <% end %>

            <div class="carousel-caption image_caption">
              <h3><strong><%= "#{movie.title} (#{movie.year})" %></strong></h3>           
            </div>
          </div>
        <% else %>
         <div class="item">
           <% if movie.image_file_name%>
             <a href= <%=movie_path(movie) %>>
                <img class="img-responsive center-block" src= <%="#{movie.image.url(:medium)}"%> alt=<%="#{movie.title}"%> width="400" height="600">
             </a>
           <% else %>
             <a href=<%=movie_path(movie) %>>
                <img class="img-responsive center-block" src= <%="#{url_to_asset("no-movie")}"%> alt=<%="#{movie.title}"%> width="400" height="600">
             </a>
           <% end %>
           <div class="carousel-caption image_caption">
             <h3><strong><%= "#{movie.title} (#{movie.year})" %></strong></h3>         
           </div>
         </div>
       <% end %>
     <% end %>
   </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#mySlider" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#mySlider" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<script>
  $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score')
      }
  });
</script>

app/views/movies/new.html.erb
<html>
  <div class="jumbotron">
    <h1>New Movie</h1>

    <%= render 'form', movie: @movie %>

    <%= link_to 'Back', movies_path %>
  </div>
</html>

app/views/movies/show.html.erb
<head>
  <style>
    body {
      <% if @movie.image_file_name %>
        background:  url(<%= @movie.image.url(:original) %>) no-repeat center center fixed;
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
        background-size: cover
     <% end %>
   }
  </style>
</head>

  <div class="movie-info">
    <div class="row">
      <div class="col-md-4">
        <% if @movie.image_file_name%>
          <%= image_tag @movie.image.url(:medium) %>
        <% else %>
          <%= image_tag url_to_asset("no-movie"), :size => "400x600" %>
        <% end %>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1><%= @movie.title %></h1>
        <% if user_signed_in? %>
          <% if @want %>
            <p> <%= link_to "Want to See", new_movie_want_to_see_path(@movie), class: "btn btn-danger" %> </p>
          <% end %>
        <% end %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Avg. ratting:</strong></td>
                <td>
                  <div class="star-rating" data-score=<%= @movie.avg_ratting %> ></div>
                  <em><%="#{@reviews.length} reviews" %></em>
                </td>
              </tr>
              <tr>
                <td><strong>Category:</strong></td>
                <td><%= @movie.category.name %></td>
              </tr>
              <tr>
                <td><strong>Year:</strong></td>
                <td><%= @movie.year %></td>
              </tr>
              <tr>
                <td><strong>Length (min):</strong></td>
                <td><%= @movie.lengthMinutes %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td><strong><%= link_to (@movie.director.name +  " " + @movie.director.surname), @movie.director, :style=> 'color: #0000ff' %> </strong></td>
              </tr>
              <tr>
                <td><strong>Actors / Actresses:</strong></td>
                <td>
                  <% @movie.actors.each do |actor| %>
                    <strong><%= link_to (actor.name +  " " + actor.surname), actor, :style=> 'color: #0000ff' %> </strong>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
            </tbody>
          </table>
          <% if @write %>
          <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

    <div class="reviews">
      <h1>Reviews</h1>
      <% if @reviews.blank? %>
        <h3>No reviews yet, would you like to add a review?</h3>
        <% if user_signed_in? %>
          <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Sing up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
        <% end %>
      <% else %>
        <% @reviews.each do |review| %>
          <div class="review">
            <div class="star-rating" data-score=<%= review.rating%>> <b><%= review.user.nickname %> </b> </div>
            <p><%= review.comment %></p>
            
            <% if user_signed_in? %>
              <% if review.user_id == current_user.id %>
                <div class="links btn-group">
	                <%= link_to "Edit", edit_movie_review_path(review.movie, review) %> |
		              <%= link_to "Delete", movie_review_path(review.movie, review), method: :delete, data: { confirm: " Are you sure to remove this review?" } %>
	             </div>
	           <% end %>
	         <% end %>   
          </div>
        <% end %>
        <%= will_paginate @reviews, renderer: BootstrapPagination::Rails,
        :param_name => 'reviews', previous_label: "Prev", next_label: "Next",
        inner_window: 1, outer_window: 0 %> 
      <% end %>
     </div> 
     
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
  <%= link_to 'Delete', @movie, method: :delete, data: { confirm: 'Are you sure to delete this movie?' } %> |
<% end %>
<%= link_to 'Back', movies_path %>

<script>
  $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score')
      }
  });
</script>