config/routes.rb
Rails.application.routes.draw do

  resources :want_to_sees, except: [:show, :new, :create, :edit, :update]
  resources :actors, except: [:index]
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :directors, except: [:index]
  get "search" => "search#search", :as => :search

  resources :movies do
    resources :reviews, except: [:show, :index]
    resources :want_to_sees, only: [:new, :create, :edit, :update]
  end

  root 'movies#index'
end

app/models/director.rb
class Director < ApplicationRecord
  validate :date_validation
  has_many :movies

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates_presence_of :name, :surname, :biography

  def date_validation
    if birth.nil?
      errors.add(:birth, 'Birth must be set')
    elsif birth >= Date.today
      errors.add(:birth, 'Birth can not be in future or today')
    end
  end

  def age
    today = Date.today
    age = today.year - birth.year
    age -= 1 if Date.today < (birth + age.years)
    age
  end

  def select_label
    "#{name} #{surname} " + birth.strftime("%d.%m.%Y")
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  def destroy
    if @director.movies.empty?
      @director.destroy
      respond_to do |format|
        format.html { redirect_to movies_path, notice: 'Director was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @director, notice: 'Director could not be destroyed (He is assign to some movie).' }
        format.json { render :show, status: :created, location: @director }
      end
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @movies = {}
    @director.movies.each do |m|  # Movie.where(director_id: @director.id)
      if @movies.key?(m.year)
        @movies[m.year].add(m)
      else
        @movies[m.year] = Set.new
        @movies[m.year].add(m)
      end
    end
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1
  # PATCH/PUT /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def director_params
      params.require(:director).permit(:name, :surname, :birth, :biography, :image)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<head>
</head>

<%= simple_form_for @director, html: { multipart: true } do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Name', error: 'Name of director must be set.' %>
    <%= f.input :surname, label: 'Surname', error: 'Surname of director must be set.' %>
    <%= f.input :birth, as: :date, html5: true, label: 'Birth', error: 'Birth of director must be set.'  %>
    <%= f.input :biography, label: 'Biography', error: 'Biography of director must be set.' %>
    <%= f.input :image, label: 'Image', error: 'Image must be set' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn btn-danger" %>
  </div>
<% end %>

app/views/directors/edit.html.erb
<html>
  <div class="jumbotron">
    <h1>Edit Director</h1>

    <%= render 'form', director: @director %>

    <%= link_to 'Back', @director %>
  </div>
</html>

app/views/directors/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

app/views/directors/new.html.erb
<html>
  <div class="jumbotron">
    <h1>New Director</h1>
    
    <%= render 'form', director: @director %>
    
    <%= link_to 'Back', movies_path %>
  </div>
</html>

app/views/directors/show.html.erb
<head>
  <style>
    body {
      background: url(asset-path('backround-director.jpg')); no-repeat center center fixed; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
      background-size: cover;
    }
  </style>
</head>


  <div class="director-info">
    <div class="row">
      <div class="col-md-2">
        <% if @director.image_file_name%>
          <%= image_tag @director.image.url(:medium), :size => "225x300" %>
        <% else %>
          <%= image_tag url_to_asset("no-person"), :size => "225x300" %>
        <% end %>
      </div>

      <div class="col-md-8 col-md-offset-1">
        <h1 class: "btn btn-danger"><%= @director.name + " " + @director.surname %></h1>

        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Director</strong></td>
                <td></td>
              </tr>
              <tr>
                <td><strong>Name:</strong></td>
                <td><%= @director.name %></td>
              </tr>
              <tr>
                <td><strong>Surname:</strong></td>
                <td><%= @director.surname %></td>
              </tr>
              <tr>
                <td><strong>Birth:</strong></td>
                <td><%= @director.birth.strftime("%d.%m.%Y") + " ( age: " + @director.age.to_s + " )" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_director_path(@director) %> |
      <%= link_to 'Delete', @director, method: :delete, data: { confirm: 'Are you sure to delete this director?' }%>
    <% end %> |
    <%= link_to 'Back', movies_path %>
  </div>  

    
<div class="col-md-8">
  <div class="director-biography">
    <tr>
      <p></p>
      <h5><strong>Biography:</strong></h5>
      <p></p>
      <td><%= @director.biography%></td>
    </tr>
  </div>
</div>

<div class="col-md-4">
  <div class="director-list-movies">
    <h5><strong>List of movies</strong></h5>
    <div class="table-responsive">
      <table class="table">
        <tbody>
          <% if @director.movies.empty? %>
            <h3>No movie</h3>
          <% else %>

            <% @movies.each do |k, set| %>
                <tr>
                  <td><strong><%= k %></strong></td>
                  <td>
                    <% set.each do |movie| %>
                      <p>
                        <div class="star-rating" data-score= <%= movie.avg_ratting %> > 
                          <strong><%= link_to (movie.title), movie, :style=> 'color:#0000ff' %> </strong>
                        </div>
                      </p>
                    <% end %>
                  </td>
               </tr>    
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score')
      }
  });
</script>